#!/bin/bash
mkdir QAC_mubeen
cd QAC_mubeen
touch file1 file2 file3
echo "text 1" >> file1
echo "text 2" >> file2
echo "text 3" >> file3
mkdir childDir
cp ~/projects/linux-tasks/QAC_mubeen/file{1..3} ~/projects/linux-tasks/QAC_mubeen/childDir/

